version: '3.8'

services:
  # Spring Boot Application
  grocery-backend:
    build: ./grocery-backend
    container_name: grocery-backend
    image: grocery-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/grocery_db?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=groceryuser
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - mysql
    networks:
      - backend-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=grocery_db
      - MYSQL_USER=groceryuser
      - MYSQL_PASSWORD=admin
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network

  # Frontend Application (Vite)
  frontend:
    build:
      context: ./grocery-frontend  # Path to the Vite app directory
    container_name: grocery-frontend
    image: grocery-frontend
    ports:
      - "5173:5173"  # Assuming Vite runs on port 3000
    networks:
      - backend-network
    command: ["npm", "run", "dev", "--", "--host"]

networks:
  backend-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
