version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=gms
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "nc", "-z", "mysql-db", "3306" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local